### ISSUE TITLE
Having problems with Nuxt/Vue files

### ISSUE THREAD

**Issue by luisfrocha** [zakissimo/hook.nvim#1]
*This is my first issue submission ever, and I don't see others listed, so let me know if the format should be different.*

I have some buffers that are being closed automatically when I open them. The pathnames of the files include the single or double brackets, and I think that's what's throwing it off. I.E.: `pages/level1/[id1]/level2/[id2]/[[type]]/index.vue`. When I activate hook, it shows the buffer, but when I select it and open it, it throws an error and immediately closes the buffer.

Not sure if I should submit another issue, but also, if I have the buffer open and I activate hook, but then ESCape without selecting another buffer, it automatically closes the above mentioned buffer, which includes the brackets. This only happens with files which have brackets in the pathname.

One additional detail, but not sure if it is a factor, is that I am using Bufferline, and after I open the buffer and I see the tab on the tab line, I activate Hook but it doesn't list that buffer (the one with brackets in the pathname). However, if I open that file and cycle through the tabs, after I pass that file (with brackets), and activate Hook, it gets listed. It still closes when I try to open it, though.

In case it's a factor, I also changed the key map to activate Hook with `<C-tab>`. I doubt it's an issue, but thought I'd also list it.

I will attach images when I switch to my personal computer as I'm not able to share screenshots of my codebase.

**Comment by zakissimo** [comment]
Hi! It's my first public / open source project, so I don't really have a norm on issue submission! That being said, thank you for the detailed analysis on the problem. I do see exactly where it comes from. I use regex to get the name of the file from the hook window and in case you deleted an entry, it then closes the corresponding buffer. And you are right, I only accept alphanumeric characters which is obviously a problem. I will fix it as soon as possible.

**Comment by luisfrocha** [comment]
Awesome! Thank you!

**Comment by zakissimo** [comment]
Okay works on my end, I pushed changes. Update the plugin and do tell me if you still have a problem!

**Comment by luisfrocha** [comment]
Perfect! Thank you!
